
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import integration.UserRegistrarServerTest;
import unit.UserRegisterHandlerTest;

@RunWith(Suite.class)
@Suite.SuiteClasses({ UserRegistrarServerTest.class, UserRegisterHandlerTest.class })
public class AppTest {

}
