
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import integration.EventReceiverServerTest;
import integration.UserRegistrarServerTest;
// @Suite.SuiteClasses({ UserRegistrarServerTest.class })

@RunWith(Suite.class)
@Suite.SuiteClasses({ UserRegistrarServerTest.class, EventReceiverServerTest.class })
public class IntegrationTest {

}
