
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import integration.UserRegistrarServerTest;

@RunWith(Suite.class)
@Suite.SuiteClasses({ UserRegistrarServerTest.class })
public class IntegrationTest {

}
